version: "3.8"

services:
  # property-listing-frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - BACKEND_API_URL=http://property-listing-backend:8080
  #   depends_on:
  #     - property-listing-backend

  # property-listing-backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=development
  #     - MONGO_URI=mongodb://boomershub:Xq0gYvRjCTxHKzyB@mongodb:27017/property-listing?authSource=admin
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: boomershub
      MONGO_INITDB_ROOT_PASSWORD: Xq0gYvRjCTxHKzyB
      MONGO_INITDB_DATABASE: property-listing
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
